# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b11a1e9ae1cb224803ecbfe37dde60b989d48f718eb122774c124737dce44b560a3cf2962d7dd91f9a36cddbbc2697445ffc92b42e0e40e20d917c1773847bff

test:
  secret_key_base: cec10e44c26eabee717430241954a47d6d053d55a13622c34281e64a6470ab87061ebc8d0722d4fbae130a23bdb10d7c850fccc76063f39e904593c74b0502a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
